name: Desktop tool tests
description: Test the MPC Autofill CLI / desktop tool
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      working-directory: desktop-tool
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run tests
      run: |
        cd desktop-tool && pytest .
      shell: bash
