name: Frontend tests
description: Test the MPC Autofill static frontend
runs:
  using: composite
  steps:
    - name: Install npm
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Compile frontend
      working-directory: frontend
      run: |
        npm ci
        npm run build
      shell: bash
    - name: Run frontend tests
      working-directory: frontend
      run: |
        npm run test
      shell: bash
