name: Formatting and static type checking
description: Validate code styling and type safety with pre-commit hooks
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash
    - name: Run pre-commit
      run: pre-commit run --all-files
      shell: bash
