name: Backend tests
description: Test the MPC Autofill Django backend
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-chrome@latest
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      working-directory: MPCAutofill
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Install Elasticsearch
      run: |
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.6-amd64.deb -q
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.6-amd64.deb.sha512
        shasum -a 512 -c elasticsearch-7.17.6-amd64.deb.sha512
        sudo dpkg -i elasticsearch-7.17.6-amd64.deb
      shell: bash
    - name: Start Elasticsearch
      run: sudo systemctl start elasticsearch.service
      shell: bash
    - name: Install npm
      uses: actions/setup-node@v3
    - name: Compile frontend
      working-directory: MPCAutofill
      run: |
        npm ci
        npm run build
      shell: bash
    - name: Write Google Drive API credentials to file
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "client_secrets.json"
        json: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
        dir: "MPCAutofill/"
    - name: Run Django integration tests
      run: |
        cd MPCAutofill && pytest .
      shell: bash
