# credit: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
name: MPC Autofill Desktop Client
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: autofill
            name: Desktop Client
          - package: MPCAutofill
            name: Django Project
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies for ${{ matrix.name }}
        working-directory: ${{ matrix.package }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort
      - name: Run tests for ${{ matrix.name }}
        run: |
          cd ${{ matrix.package }} && pytest .
  pre-commit:
    name: Auto-format project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: autofill
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            OUT_FILE_NAME: autofill
          - os: windows-latest
            TARGET: windows
            OUT_FILE_NAME: autofill.exe
          - os: ubuntu-latest
            TARGET: linux
            OUT_FILE_NAME: autofill
    steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-chrome@latest
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller for ${{ matrix.TARGET }}
      run: pyinstaller autofill.spec
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./autofill/dist/${{ matrix.OUT_FILE_NAME }}
        name: autofill-${{ matrix.TARGET }}
