name: Django project tests
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        working-directory: MPCAutofill
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Elasticsearch
        run: |
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.6-amd64.deb
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.6-amd64.deb.sha512
          shasum -a 512 -c elasticsearch-7.17.6-amd64.deb.sha512
          sudo dpkg -i elasticsearch-7.17.6-amd64.deb
      - name: Start Elasticsearch
        run: sudo systemctl start elasticsearch.service
      - name: Write Google Drive API credentials to file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "client_secrets.json"
          json: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          dir: 'MPCAutofill/'
      - name: Run tests
        run: |
          cd MPCAutofill && pytest .
