name: Backend tests
on:
  pull_request:
    paths:
      - "MPCAutofill/**"
  workflow_dispatch:
jobs:
  test-backend:
    name: Backend tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          DATABASE_NAME: mpcautofill
          DATABASE_USER: mpcautofill
          DATABASE_PASSWORD: mpcautofill
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-backend
        with:
          google-drive-api-key: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
