name: Tests
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  test-backend:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-backend
  test-desktop-tool:
    name: Desktop tool tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-test-desktop-tool
  test-frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-frontend
  test-pre-commit:
    name: Formatting and static type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-pre-commit
