name: Backend tests
on:
  pull_request:
    paths:
      - "MPCAutofill/**"
  workflow_dispatch:
jobs:
  test-backend:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-backend
