name: MPC Autofill Tests, black, isort, and mypy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: autofill
            name: Desktop Client
          - package: MPCAutofill
            name: Django Project
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies for ${{ matrix.name }}
        working-directory: ${{ matrix.package }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort
      - name: Run tests for ${{ matrix.name }}
        run: |
          cd ${{ matrix.package }} && pytest .
  pre-commit:
    name: black, isort, and mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
